seq = 'CTCAATTTTCGAGAAACGGTAAAGGTCTAAGATCCACAACAGACAATTCCGAGGATAGCAGGTATTGGACCCGCCGCCAACAGATGCCCGTTTCGGTAAAAATGTGAGAGGCCCCACAAAACAGCATTGCTCTAGGCGATAGCGGAAGCACGGTGATCAGTAAGCTGCAAAAGGGCCTCAGACATCTATCCCAGATACGGTAGCCTGGCGCCCTTTCATTAGATCCGTACAACCTGACGCATGTAGTACGCGCGGCCAAATCAAGATTCGAACCTATACAGACGGTAATTACTGAAACGCGGACCTACTTATGAACGGGTTAATGTCGTATCTGGCATAAAAATAAACGAGGTCTATCTCACCAAAGAGAAGTTACTCTGTCCGGGCGGCGGACAAATCGCTGAATGGGGAATTATAGTCACGGCTCCTTCTGAACGGTAGACCACAGGCAGGTACGTCGCCGTTTAATACGAGTCTTCGAGCAAGTGATCTCGAGAAAGGTGCCGGGGTGCGGTCAGCCGAGCGGGTATCATAGGAGCTCTAGATCCGCACTTGTGGTGCCCTTTCCGCACGCGACCACCAGGCCGTCCTTTCTAACGACCTTGTCATAGAACGTTAACAGGGAGGTATTAAGCCTATGAACACGACTCTTAAGCAACGGGGTTCAATCCTTGCCCATTGTGCTTCGACACAATTGACTCCGGCCCTACTCTCTTCCCGACAGTTGCCTCATTATCAACTGGACGCCACATGCGGGATACAAATAGATGTGCTAGTGATTCAGAAGTGGCGTTGTATTAGGCCGCATCGCTTCATAACCCTTATTTTGTCATCCGGACATCAACCTGTACAAGTAATGTCGATACCATGATGAACCCCCCGTCCGGACCAAAGTCTGAGCCCCTATAGGGAAGTCAGTTTCTCTATGTATG'

def DNA_nucleotide_count(seq):
    """
    (str) -> int int int int
    Returns the values of the nucleotide frequency for sequence seq.
    """
    d = dict([
        ('A',seq.count('A')),
        ('T',seq.count('T')),
        ('G',seq.count('G')),
        ('C',seq.count('C'))
        ])

    return d['A'], d['C'], d['G'], d['T']

a, c, g, t = DNA_nucleotide_count(seq)

print(a, c, g, t)
