dna = 'CCCACCTCATTCGCAGCTGATATACATGACCGCGCGCAGAAACTGGAGAAAGGCGGCAAGATGACGTTGAGAGAAGAGCGGCCAGTCGGATGCGTCCGCTAGGAGGATTAGAGGAATATTACCGGTGGTAGAAGATGTACAAGGGCATAGAATGACATATAAACAATGGTAGCTTACGCTCCCGTGAACGGGTTGTGCATTCCGAGTCCCGCGACTAAGGACCGTGATCGGTTGACGGCGCGCACAGCAGTTTGTAGTTTCTTCAAAATATGCATTAAAATGAGGATTCGTAATGCCGCCAATGGGCCCCGCAAGGGGCATTTATCTCTAAGGGTAAGATTTCTAAATGCGAGCCTGTTAGTAGGTGCGATGGAGCACACCCCTGTAGTAGATTAGAGAAGTGGACTAGTAGTTAAGATCTTCTTCACGACCCCTAGGTGGGCGCTCGCTACATAAGACTACGACCCAATCGCATGGGTCCTAATATCCTTTCCGTACTTCACTATCTTAGCGTGTCCTGTCCCGCACATCAATTTGTCTTTGAGCAAGAGTATCATTCGAGTAGGTGACCTCTACGGTGCACTATCACTGCTAACCCTTTCACTTTTAAAGCTGTCTGCGCGCCCTGTGCAGACGGAGTATCGCCTTCAGGACGTTAGGGGCTCCGCCTTCTATTTGATAATTAATTTCACAGTTTACGTTCTTCGTATCTACCGTCTACCCAGTATATCAATACCATGATGCGTGGGACACGGGCAAATAAGCATCAAACCAACGTATTGGTATCCAAGGCGTTTCGCCCGGAACTAAGGCACAGTCGGCCAACAAACACCTCTGCCGAGCCGGACTCAACTATGACAAGTACTGCATTGCGTCCCCTCCTGTTTGTAGCGTTATTTTAATAGTATGAATCCTGAATGGGGACCCCGGCACCCTCAAGAATCCTCCCAGATCTATTGAGTGAGGCGTCC'


def transcribe(dna):
    acg = 'ACG'
    rna = ''
    for nt in dna:
        if nt in acg:
            rna += nt
        elif nt == 'T':
            rna += 'U'

    return rna

transcript = transcribe(dna)
print(transcript)
        
















