'''
Transcribing DNA into RNA

Problem
An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.

Given a DNA string t corresponding to a coding strand, its transcribed RNA string u is formed by replacing all occurrences of 'T' in t with 'U' in u.

Given: A DNA string t having length at most 1000 nt.

Return: The transcribed RNA string of t.

Sample Dataset
GATGGAACTTGACTACGTAAATT

Sample Output
GAUGGAACUUGACUACGUAAAUU
'''

dna = 'CCCACCTCATTCGCAGCTGATATACATGACCGCGCGCAGAAACTGGAGAAAGGCGGCAAGATGACGTTGAGAGAAGAGCGGCCAGTCGGATGCGTCCGCTAGGAGGATTAGAGGAATATTACCGGTGGTAGAAGATGTACAAGGGCATAGAATGACATATAAACAATGGTAGCTTACGCTCCCGTGAACGGGTTGTGCATTCCGAGTCCCGCGACTAAGGACCGTGATCGGTTGACGGCGCGCACAGCAGTTTGTAGTTTCTTCAAAATATGCATTAAAATGAGGATTCGTAATGCCGCCAATGGGCCCCGCAAGGGGCATTTATCTCTAAGGGTAAGATTTCTAAATGCGAGCCTGTTAGTAGGTGCGATGGAGCACACCCCTGTAGTAGATTAGAGAAGTGGACTAGTAGTTAAGATCTTCTTCACGACCCCTAGGTGGGCGCTCGCTACATAAGACTACGACCCAATCGCATGGGTCCTAATATCCTTTCCGTACTTCACTATCTTAGCGTGTCCTGTCCCGCACATCAATTTGTCTTTGAGCAAGAGTATCATTCGAGTAGGTGACCTCTACGGTGCACTATCACTGCTAACCCTTTCACTTTTAAAGCTGTCTGCGCGCCCTGTGCAGACGGAGTATCGCCTTCAGGACGTTAGGGGCTCCGCCTTCTATTTGATAATTAATTTCACAGTTTACGTTCTTCGTATCTACCGTCTACCCAGTATATCAATACCATGATGCGTGGGACACGGGCAAATAAGCATCAAACCAACGTATTGGTATCCAAGGCGTTTCGCCCGGAACTAAGGCACAGTCGGCCAACAAACACCTCTGCCGAGCCGGACTCAACTATGACAAGTACTGCATTGCGTCCCCTCCTGTTTGTAGCGTTATTTTAATAGTATGAATCCTGAATGGGGACCCCGGCACCCTCAAGAATCCTCCCAGATCTATTGAGTGAGGCGTCC'

def transcribe(dna):
    acg = 'ACG'
    rna = ''
    for nt in dna:
        if nt in acg:
            rna += nt
        elif nt == 'T':
            rna += 'U'

    return rna

transcript = transcribe(dna)
print(transcript)

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# another solution (more pythonic this time)
u = 'GAUGGAACUUGACUACGUAAAUU'
t = 'GATGGAACTTGACTACGTAAATT'

def transcribe(t):
	'''Return the transcribed RNA string of t DNA string.'''
	return t.replace('T', 'U')

uu = transcribe(t)
print(u)

print(uu == u)
















