#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  1 08:53:22 2021

@author: alina

Counting Point Mutations

Problem
Given two strings s and t of equal length, the Hamming distance between s and t,
denoted dH(s,t), is the number of corresponding symbols that differ in s and t

Given: Two DNA strings s and t of equal length (not exceeding 1 kbp).

Return: The Hamming distance dH(s,t).

Sample Dataset
GAGCCTACTAACGGGAT
CATCGTAATGACGGCCT

Sample Output
7
"""

s = 'GAGCCTACTAACGGGAT'
t = 'CATCGTAATGACGGCCT'

def hamming_distance(s, t):
    '''
    (str, str -> int)
    Return the number of corresponding symbols that differ in s and t
    (the Hamming distance dH(s,t)) for 2 DNA strings s and t of equal length.
    '''
    count = 0
    
    for i in range(len(s)):
    	if s[i] != t[i]:
    		count += 1
    
    return count

hamming_distance(s, t)

s = 'TTTTGGTGGTTCTCCTAAAATTCGAGGGTCGATCCAAGAAGGAACTAAGGGACCCATTGGTACCGCGGGACGCTTTCAGTCTATCCGTTTACGGGGATCGCGCCATGAGGCTTTTTCCTGTGGTTCAGGATCCCGTCGTCTTCGCTCTCCCAATATGGTAAACCATATGGTCCAATGTCCAGTAAGAGGACAACGTTCGAAACCCAGGCTTACCGTTTCAGAGCAGGACGGAATGGTGTCACTTTGCGGGCTGCACTGAACCCGACAGCCAACCTGATGCTAAATGGATGGAGTCCTCCACAGGGTAGCCAGTCATGGAGAGTTGTCGATTGAGTGGGGTTAATCATGGCTTCTCCCCTAGTAATGAACACCCATTTCCTAGCATCTTGCAACGCGTACTCGAATACAAAGCTTTGAAATTCAAAACCGTGGTTTTCGGTGGGCCTGGAGATAACGTATACCAAATCTCTGAGGGCGGCAGATAAGTGATAGGCCTGTTAAGGCGCAGAATCCACGTCTGCCCTGTCATTGACAGAGGAAACGGCCCAGTTGGTGCGGATGCACTACTTCACCGGGTAACAGTCCCATTATCTGCTATTCGGACTAGAAACGTTTGCCGAGTGCATAAATGCAAAGAGGTCCGTACTGCGCCTTGGGAAACACACTCGAATTGAGGGTCACATAGCGGAGTGGAGGTGGAAGAAGGAGTCTGGCGCTTGGTACCCTTGGGTCTGTCACCCGAAGCCGTCCGATGGTAACGCCGAGCACAAGGATTCCCGATGGGGGCATGCAACTTCGAGAGAACAGCTCTATTCGCCGAAAAACTTATCGTACACCTGCACCTAAGGTAAGGATCACGCGAGCAGGGAGAATACCCGTTCCGCCAAACTGGAGCGCGGTTCTA'
t = 'TTTAATAAGATGCCTCCTATTTCCCCCTCCAATCGACCTCTGCGTCCAGGCGGCAGTGGGCAGAGCACGGTATCCTACGAAATTCCGAAGGTAGCGCTCGTAAATCGTGTTCCAACCCTGCGGATGCTGGTCCAATCTTCTGCAAGTTCCCTATGCGGTCCACCCCAGGAGAGTGTATCCAGGGAGAGACCGACCATGTTACAACTAGACTATCTTATGATGCGACGTGGCAAGGGTGCCACTTTTATAAAGGTCACGGTGCGGGCTTACAAACCTAGGTTTCAGTGTTGGATTCGTCCGCCAGAGATTAATACTTAGGTTGGTGTCGATATAGTTGAATCAGGGGGGGTGTCCTCGCAGCGAGGGGATACTCATTGCTTGACGGCCTACAGATAACTCTCCGAGACACAGCATTGAAACCCACTACCCCGGATGTGTGTTTGACTGAGGCGGGAGCATAGCCAAACCCCAACGGACCAAGTTAAGACTTAGATCGCTTCTGTCACGTGGTCCCCGACGTACCTCCCATCTTCATCGGACACTACCGTGAAGACGCAGCCGATTTAGATACATGGGCAGGAGGCCCAGCAGGTGCTCTCCGCCTTAGCGGCGTTGGACAAGTCCCTAAATGTAATGCATTCCGTATCCCTCATTGAAAAACGACCTATTAGTGACACTCACTGACCGGGGTGGAGGTGCAGGTAAAAGGCAGACGTCGTGTGCTGTTTCGCTCACCGCCTGCGCCCGTGCGTCCGTAACGCAGAGTGCCCGTACGGGTGGCGCGGACTTGCTACGGCGCGTGAAGAGTTCTGTAAGCGTAAATGCTGTTCATAACCTTACAAGTACAATACCGCGTAGCTCACCTTGGTGAATAGCCTCCCCGCGAAACCGTAACACGTAGCCA'

